In [ ]:
from sklearn import datasets
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

In [ ]:
X, y = data = datasets.make_classification(n_samples=100, n_features=3, n_informative=3, n_redundant=0, n_repeated=0, n_classes=2, n_clusters_per_class=2, weights=None, flip_y=0.01, class_sep=2.0, hypercube=True, shift=0.0, scale=1.0, shuffle=True, random_state=None)

In [ ]:
fig1 = px.scatter_3d(x =X[:,0], y = X[:,1], z = X[:,2],color = y)
fig1.show()

In [ ]:
X1 = X[y==0]
X2 = X[y==1]

In [ ]:
def mean_calc(x):
  mean = np.ndarray(shape=(1,len(x[0])))
  for i in range(len(x[0])):
    mean[0][i] = np.mean(x[:,i])
  return np.array(mean)

mean_x1, mean_x2 = mean_calc(X1), mean_calc(X2)

In [ ]:
mean_x1

array([[-0.2008601 ,  1.8017887 , -1.78055792]])

In [ ]:
cov_x1, cov_x2 = pd.DataFrame(X1).cov().values, pd.DataFrame(X2).cov().values
total_cov = cov_x1 + cov_x2

In [ ]:
total_cov

array([[ 9.86306574,  0.9245135 , -5.08714934],
       [ 0.9245135 ,  1.22328568, -1.16551109],
       [-5.08714934, -1.16551109,  8.53391815]])

In [ ]:
sb = np.multiply(mean_x1-mean_x2,np.transpose(mean_x1-mean_x2))
sb

array([[ 0.02812465, -0.66814994,  0.30781891],
       [-0.66814994, 15.87306054, -7.312772  ],
       [ 0.30781891, -7.312772  ,  3.36901848]])

In [ ]:
np.linalg.inv(total_cov)

array([[ 0.1474716 , -0.0318392 ,  0.08356081],
       [-0.0318392 ,  0.94662904,  0.11030524],
       [ 0.08356081,  0.11030524,  0.18205568]])

In [ ]:
eva_mat = np.multiply(np.linalg.inv(total_cov),sb)

In [ ]:
eigen_values, eigen_vector = np.linalg.eig(eva_mat)

In [ ]:
eigen_values

array([2.84511770e-03, 5.69620321e-01, 1.50709311e+01])

In [ ]:
eigen_vector

array([[-0.99887246,  0.04745618, -0.00131465],
       [ 0.00395465,  0.05557934, -0.99844644],
       [ 0.04730938,  0.99732585,  0.05570434]])

In [ ]:
_X1 = np.dot(X1,np.transpose(eigen_vector[1:]))
_X2 = np.dot(X2,np.transpose(eigen_vector[1:]))

In [ ]:
fig3 = px.scatter(x = X1[:,0], y = _X1[:,1],color=[0]*len(_X1),size=[10]*len(_X1))
fig4 = px.scatter(x = X2[:,0], y = _X2[:,1],color=[1]*len(_X2),size=[10]*len(_X2))
fig = go.Figure(data = fig3.data + fig4.data)
fig.show()